name: restic backup action
description: Backup a repo with restic
author: Sascha Mann

branding:
  icon: save
  color: green

inputs:
  token:
    description: GitHub access token
    default: ${{ github.token }}
    required: true

runs:
  using: composite
  steps:
    - name: Install dependencies
      run: |
        sudo apt-get install restic
        pip install github-backup
      shell: bash

    - name: Check if repo already exists
      id: existance
      run: |
        if restic snapshots; then
          echo "::set-output name=exists::true"
        fi
      shell: bash

    # Conditional steps are not allowed in composite actions
    - name: Initialise repo if it doesn't exist
      run: |
        if [ "${{ steps.existance.outputs.exists }}" != 'true' ]; then
          restic init
        fi
      shell: bash

    - name: Download GitHub data using github-backup
      run: |
        github-backup \
          --token "$INPUT_TOKEN" \
          --incremental \
          --all \
          --repository "$(basename ${{ github.repository }})" \
          --as-app \
          ${{ github.repository_owner }}
      shell: bash
    
    - name: Upload to backup repo
      run: |
        restic --verbose backup --tag gha .
      shell: bash
    
    # https://restic.readthedocs.io/en/latest/060_forget.html#removing-snapshots-according-to-a-policy
    - name: Remove old snapshots according to policy
      run: |
        restic forget \
          --tag gha \
          --keep-daily 7 \
          --keep-weekly 5 \
          --keep-monthly 12 \
          --keep-yearly 10 \
          --prune
      shell: bash
    
    - name: Check integrity
      run: restic check
      shell: bash
